const OK = 200;
const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const INTERNAL_SERVER = 500;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const REQUEST_CONFLICT = 409;

module.exports = {
  OK,
  BAD_REQUEST,
  NOT_FOUND,
  INTERNAL_SERVER,
  UNAUTHORIZED,
  FORBIDDEN,
  REQUEST_CONFLICT,
};
